import type { FieldType } from '@pulse/contracts';

export const FIELD_TYPE_OPTIONS: Array<{ value: FieldType; label: string }> = [
  { value: 'short_text', label: 'short text' },
  { value: 'long_text', label: 'long text' },
  { value: 'number', label: 'number' },
  { value: 'date', label: 'date' },
  { value: 'time', label: 'time' },
  { value: 'boolean', label: 'yes / no' },
  { value: 'rating', label: 'rating (2–10)' },
  { value: 'nps', label: 'net promoter score (0–10)' },
  { value: 'performance_level', label: 'performance level' },
  { value: 'select', label: 'choice (one answer)' },
  { value: 'multi_select', label: 'choice (multiple answers)' },
  { value: 'likert', label: 'likert matrix' },
  { value: 'grid', label: 'grid (multiple choice / checkbox)' },
  { value: 'ranking', label: 'ranking' },
  { value: 'file', label: 'file upload' },
  { value: 'section_header', label: 'section heading (no answer)' },
  { value: 'slider', label: 'slider' },
  { value: 'contact_info', label: 'contact info (name / email / phone)' },
  { value: 'hot_spot', label: 'hot spot (click a region on an image)' },
];

export const FIELD_TYPE_ICON: Record<FieldType, string> = {
  short_text: '—',
  long_text: '☰',
  number: '#',
  date: '📅',
  time: '🕐',
  boolean: '◐',
  rating: '★',
  nps: '📊',
  select: '◉',
  multi_select: '☑',
  likert: '▤',
  grid: '▦',
  ranking: '↕',
  file: '📎',
  section_header: 'Tt',
  slider: '🎚',
  contact_info: '👤',
  hot_spot: '⌖',
  person: '🧑',
  performance_level: '🏆',
};
